### ISSUE TITLE
Explode polygon tool: modify default visualization style

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/kimu#17]
Style should contain following components:

- [x] vertexes as points (possibly red?)
- [x] vertex lines (same colour as vertex points)

Let's stick to default point sizes and default line widths. This style should be always implemented as default when producing the result.

**Comment by pavetsu14** [comment]
@japeki Would you like this modification to be applied only at visualization style level or rather to change the tool so, that it genuinely produces two layers as output (one for vertex points and one for the exploded line features)?

**Comment by japeki** [comment]
> @japeki Would you like this modification to be applied only at visualization style level or rather to change the tool so, that it genuinely produces two layers as output (one for vertex points and one for the exploded line features)?

@pavetsu14 Originally I thought just changing the result visualization but I think this is better implementation. Now the resulting point layer can be used further when mapping by selecting points.
