### ISSUE TITLE
Intersect lines tool: Ability to choose intersecting lines from points

### ISSUE THREAD

**Issue by japeki** [GispoCoding/kimu#18]
- [ ] Instead of choosing two lines that intersect, additional ability to choose intersecting line or lines with point geometry.
- [ ] User should be able to choose intersecting lines with any of the following combinations: two lines, one line and two points or both lines through points.

**Comment by nmaarnio** [comment]
Regarding this issue, if intersection point is calculated from 4 points, there are multiple ways in which to interpret the imagined/extrapolated lines and therefore multiple possible intersection points. What would be the preferred way to select the wanted intersection point? Should the tool throw popup windows like some of the other tools do when there are multiple options or do you have some other idea @japeki ?

**Comment by japeki** [comment]
> Regarding this issue, if intersection point is calculated from 4 points, there are multiple ways in which to interpret the imagined/extrapolated lines and therefore multiple possible intersection points. What would be the preferred way to select the wanted intersection point? Should the tool throw popup windows like some of the other tools do when there are multiple options or do you have some other idea @japeki ?

I think pop up windows could be a good way. Currently in stellamap (program used for geodesic calculations) the tool asks to select intersecting feature(s) for first intersecting feature and then feature(s) for second intersecting feature. However this would probably change the current behaviour of the tool pretty drastically? How much additional work that would be?

Other option would be to first select all four points and after intersetion select desired intersecting point from map and additional points would disappear. However in case of four points there is 6 possible intersections which gets a bit messy. @nmaarnio
